# Generated by Django 4.1.3 on 2022-11-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_editorform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorform',
            name='resume',
            field=models.ImageField(upload_to='resume'),
        ),
    ]
